import Connection from "@/database/connection";
import Head from "next/head";
import Layout from "@/components/Layout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Layout>
        <main>
          <h1 className="text-stone-400">Hola cachito</h1>
        </main>
      </Layout>
    </>
  );
}

export async function getServerSideProps() {
  try {
    const connection = await Connection.getInstance();

    return {
      props: {
        connection: true,
      },
    };
  } catch (error) {
    console.log(error);
  }
}
